export const {
  BACKEND_URL,
  NEXTAUTH_SECRET,
  NEXT_PUBLIC_BACKEND_URL,
  NEXT_PUBLIC_SOCKET_URL,
  AUTH_SERVICE_URL,
  USERS_SERVICE_URL,
  CHAT_SERVICE_URL,
  MEDIA_SERVICE_URL,
  FILES_SERVICE_URL
} = process.env;